### ISSUE TITLE
reconstruct 

### ISSUE THREAD

**Issue by AvocadoAlpha** [yell/boltzmann-machines#16]
I am looking for something equivalent to model.predict(X_test) in keras.

`` with tf.Session():
        res = dbm.reconstruct(X_test)``

Traceback (most recent call last):
  File "/home/yunus/PycharmProjects/boltz_/boltzmann-machines-clone/examples/dbm_mnist.py", line 399, in <module>
    main()
  File "/home/yunus/PycharmProjects/boltz_/boltzmann-machines-clone/examples/dbm_mnist.py", line 377, in main
    res = dbm.reconstruct(X_test)
  File "/home/yunus/PycharmProjects/boltz_/boltzmann-machines-clone/boltzmann_machines/base/tf_model.py", line 18, in wrapped_f
    tf.reset_default_graph()
  File "/home/yunus/PycharmProjects/bo-autoencoder_1/venv2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5588, in reset_default_graph
    raise AssertionError("Do not use tf.reset_default_graph() to clear "
AssertionError: Do not use tf.reset_default_graph() to clear nested graphs. If you need a cleared graph, exit the nesting and create a new graph.

reconstruct is the equivalent i thought but i cant get it to work.
Is there a reconstruct for RBM or how is it called?

**Comment by AvocadoAlpha** [comment]
so this can be solved by training the model on your own machine. reconstruct then works.
Nevertheless one open question what is the equivalent reconstruct method for rbm ?
Thanks!!
